# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3file', models.FileField(upload_to='mp3/')),
            ],
        ),
    ]
